
enabled_mods = [
    "stairs",
    "quartz",
]

unknown_blocks = []
def convertBlock(block):
    prefix,name = block['name'].split(":")

    if name in default_table:
        return getFromTable(default_table,name,block)

    if name in ["granite","diorite","granite","andesite"]:
        return ("default:stone",255,0)

    if "_ore" in name:
        return ("default:stone_with_gold",255,0)

    if "stairs" in enabled_mods:
        if name in stairs_table:
            if block["shape"] == "straight":
                return getFromTable(stairs_table,name,block)
    
    if "quartz" in enabled_mods:
        if name in quartz_table:
            return getFromTable(quartz_table,name,block)
            
    # Unknown Block
    if block not in unknown_blocks:
        unknown_blocks.append(block)
        print("Unknown Block",block)
    return ("air",0,0)


# param conversion
def getFromTable(table,name,block):
    param0,param1,param2 = table[name]
    if callable(param2): return (param0,param1,param2(block))
    return param0,param1,param2

def cardinal2facedir(block):
    return block['north'] and 4 or block['south'] and 8 or block['east'] and 12 or block['west'] and 16

def facing2facedir(block):
    return {"north":0,"east":1,"south":2,"west":3}[block["facing"]]

def stair2facedir(block):
    return facing2facedir(block) + {"top":0,"bottom":20}[block["half"]]

def level2flowingliquid(block):
    return int(block["level"])

############
#  TABLES  #
############

default_table = {
    #"minecraft_name" : ("minetest:param0",param1,param2),
    "":("ignore",255,0),
    "air":("air",255,0),
    "cave_air":("air",255,0),
    "":("beds:bed_bottom",255,0),
    "":("beds:bed_top",255,0),
    "":("beds:fancy_bed_bottom",255,0),
    "":("beds:fancy_bed_top",255,0),
    "":("bones:bones",255,0),
    "":("butterflies:butterfly_red",255,0),
    "":("butterflies:butterfly_violet",255,0),
    "":("butterflies:butterfly_white",255,0),
    "":("butterflies:hidden_butterfly_red",255,0),
    "":("butterflies:hidden_butterfly_violet",255,0),
    "":("butterflies:hidden_butterfly_white",255,0),
    "":("carts:brakerail",255,0),
    "":("carts:powerrail",255,0),
    "":("carts:rail",255,0),
    "":("default:acacia_bush_leaves",255,0),
    "":("default:acacia_bush_sapling",255,0),
    "":("default:acacia_bush_stem",255,0),
    "":("default:acacia_leaves",255,0),
    "":("default:acacia_sapling",255,0),
    "":("default:acacia_tree",255,0),
    "":("default:acacia_wood",255,0),
    "apple":("default:apple",255,0),
    "":("default:apple_mark",255,0),
    "birch_leaves":("default:aspen_leaves",255,0),
    "birch_sapling":("default:aspen_sapling",255,0),
    "birch_log":("default:aspen_tree",255,0),
    "birch_planks":("default:aspen_wood",255,0),
    "":("default:blueberry_bush_leaves",255,0),
    "":("default:blueberry_bush_leaves_with_berries",255,0),
    "":("default:blueberry_bush_sapling",255,0),
    "bookshelf":("default:bookshelf",255,0),
    "bricks":("default:brick",255,0),
    "":("default:bronzeblock",255,0),
    "":("default:bush_leaves",255,0),
    "":("default:bush_sapling",255,0),
    "":("default:bush_stem",255,0),
    "cactus":("default:cactus",255,0),
    "":("default:cave_ice",255,0),
    "chest":("default:chest",255,0),
    "":("default:chest_locked",255,0),
    "":("default:chest_locked_open",255,0),
    "":("default:chest_open",255,0),
    "clay":("default:clay",255,0),
    "":("default:cloud",255,0),
    "":("default:coalblock",255,0),
    "cobblestone":("default:cobble",255,0),
    "":("default:copperblock",255,0),
    "bubble_coral_block":("default:coral_brown",255,0),
    "tube_coral_block":("default:coral_cyan",255,0),
    "horn_coral_block":("default:coral_green",255,0),
    "fire_coral_block":("default:coral_orange",255,0),
    "brain_coral_block":("default:coral_pink",255,0),
    "dead_bubble_coral_block":("default:coral_skeleton",255,0),
    "dead_tube_coral_block":("default:coral_skeleton",255,0),
    "dead_horn_coral_block":("default:coral_skeleton",255,0),
    "dead_fire_coral_block":("default:coral_skeleton",255,0),
    "dead_brain_coral_block":("default:coral_skeleton",255,0),
    "":("default:desert_cobble",255,0),
    "":("default:desert_sand",255,0),
    "":("default:desert_sandstone",255,0),
    "":("default:desert_sandstone_block",255,0),
    "":("default:desert_sandstone_brick",255,0),
    "":("default:desert_stone",255,0),
    "":("default:desert_stone_block",255,0),
    "":("default:desert_stonebrick",255,0),
    "":("default:diamondblock",255,0),
    "dirt":("default:dirt",255,0),
    "":("default:dirt_with_coniferous_litter",255,0),
    "":("default:dirt_with_dry_grass",255,0),
    "grass_block":("default:dirt_with_grass",255,0),
    "":("default:dirt_with_grass_footsteps",255,0),
    "":("default:dirt_with_rainforest_litter",255,0),
    "":("default:dirt_with_snow",255,0),
    "":("default:dry_dirt",255,0),
    "":("default:dry_dirt_with_dry_grass",255,0),
    "":("default:dry_grass_1",255,0),
    "":("default:dry_grass_2",255,0),
    "":("default:dry_grass_3",255,0),
    "":("default:dry_grass_4",255,0),
    "":("default:dry_grass_5",255,0),
    "":("default:dry_shrub",255,0),
    "":("default:emergent_jungle_sapling",255,0),
    "":("default:fence_acacia_wood",255,0),
    "":("default:fence_aspen_wood",255,0),
    "":("default:fence_junglewood",255,0),
    "":("default:fence_pine_wood",255,0),
    "":("default:fence_rail_acacia_wood",255,0),
    "":("default:fence_rail_aspen_wood",255,0),
    "":("default:fence_rail_junglewood",255,0),
    "":("default:fence_rail_pine_wood",255,0),
    "":("default:fence_rail_wood",255,0),
    "":("default:fence_wood",255,0),
    "":("default:fern_1",255,0),
    "":("default:fern_2",255,0),
    "":("default:fern_3",255,0),
    "":("default:furnace",255,0),
    "":("default:furnace_active",255,0),
    "glass":("default:glass",255,0),
    "":("default:goldblock",255,0),
    "":("default:grass_1",255,0),
    "":("default:grass_2",255,0),
    "":("default:grass_3",255,0),
    "":("default:grass_4",255,0),
    "":("default:grass_5",255,0),
    "gravel":("default:gravel",255,0),
    "ice":("default:ice",255,0),
    "tall_grass":("default:junglegrass",255,0),
    "jungle_leaves":("default:jungleleaves",255,0),
    "jungle_sapling":("default:junglesapling",255,0),
    "jungle_log":("default:jungletree",255,0),
    "jungle_planks":("default:junglewood",255,0),
    "":("default:ladder_steel",255,0),
    "":("default:ladder_wood",255,0),
    "":("default:large_cactus_seedling",255,0),
    "":("default:lava_flowing",255,0),
    "lava":("default:lava_source",255,level2flowingliquid),
    "oak_leaves":("default:leaves",255,0),
    "":("default:marram_grass_1",255,0),
    "":("default:marram_grass_2",255,0),
    "":("default:marram_grass_3",255,0),
    "":("default:mese",255,0),
    "":("default:mese_post_light",255,0),
    "":("default:meselamp",255,0),
    "":("default:mossycobble",255,0),
    "obsidian":("default:obsidian",255,0),
    "":("default:obsidian_block",255,0),
    "":("default:obsidian_glass",255,0),
    "":("default:obsidianbrick",255,0),
    "sugar_cane":("default:papyrus",255,0),
    "":("default:permafrost",255,0),
    "":("default:permafrost_with_moss",255,0),
    "":("default:permafrost_with_stones",255,0),
    "":("default:pine_bush_needles",255,0),
    "":("default:pine_bush_sapling",255,0),
    "":("default:pine_bush_stem",255,0),
    "":("default:pine_needles",255,0),
    "":("default:pine_sapling",255,0),
    "":("default:pine_tree",255,0),
    "":("default:pine_wood",255,0),
    "":("default:river_water_flowing",255,0),
    "water":("default:river_water_source",255,level2flowingliquid),
    "sand":("default:sand",255,0),
    "":("default:sand_with_kelp",255,0),
    "sandstone":("default:sandstone",255,0),
    "":("default:sandstone_block",255,0),
    "":("default:sandstonebrick",255,0),
    "oak_sapling":("default:sapling",255,0),
    "":("default:sign_wall_steel",255,0),
    "":("default:sign_wall_wood",255,0),
    "":("default:silver_sand",255,0),
    "":("default:silver_sandstone",255,0),
    "":("default:silver_sandstone_block",255,0),
    "":("default:silver_sandstone_brick",255,0),
    "":("default:snow",255,0),
    "":("default:snowblock",255,0),
    "":("default:steelblock",255,0),
    "stone":("default:stone",255,0),
    "":("default:stone_block",255,0),
    "coal_ore":("default:stone_with_coal",255,0),
    "copper_ore":("default:stone_with_copper",255,0),
    "diamond_ore":("default:stone_with_diamond",255,0),
    "gold_ore":("default:stone_with_gold",255,0),
    "iron_ore":("default:stone_with_iron",255,0),
    "redstone_ore":("default:stone_with_mese",255,0),
    "tin_ore":("default:stone_with_tin",255,0),
    "":("default:stonebrick",255,0),
    "":("default:tinblock",255,0),
    "":("default:torch",255,0),
    "":("default:torch_ceiling",255,0),
    "":("default:torch_wall",255,0),
    "oak_log":("default:tree",255,0),
    "":("default:water_flowing",255,0),
    "":("default:water_source",255,0),
    "oak_planks":("default:wood",255,0),
    "":("doors:door_glass_a",255,0),
    "":("doors:door_glass_b",255,0),
    "":("doors:door_obsidian_glass_a",255,0),
    "":("doors:door_obsidian_glass_b",255,0),
    "":("doors:door_steel_a",255,0),
    "":("doors:door_steel_b",255,0),
    "":("doors:door_wood_a",255,0),
    "":("doors:door_wood_b",255,0),
    "":("doors:gate_acacia_wood_closed",255,0),
    "":("doors:gate_acacia_wood_open",255,0),
    "":("doors:gate_aspen_wood_closed",255,0),
    "":("doors:gate_aspen_wood_open",255,0),
    "":("doors:gate_junglewood_closed",255,0),
    "":("doors:gate_junglewood_open",255,0),
    "":("doors:gate_pine_wood_closed",255,0),
    "":("doors:gate_pine_wood_open",255,0),
    "":("doors:gate_wood_closed",255,0),
    "":("doors:gate_wood_open",255,0),
    "":("doors:hidden",255,0),
    "":("doors:trapdoor",255,0),
    "":("doors:trapdoor_open",255,0),
    "":("doors:trapdoor_steel",255,0),
    "":("doors:trapdoor_steel_open",255,0),
    "":("farming:cotton_1",255,0),
    "":("farming:cotton_2",255,0),
    "":("farming:cotton_3",255,0),
    "":("farming:cotton_4",255,0),
    "":("farming:cotton_5",255,0),
    "":("farming:cotton_6",255,0),
    "":("farming:cotton_7",255,0),
    "":("farming:cotton_8",255,0),
    "":("farming:desert_sand_soil",255,0),
    "":("farming:desert_sand_soil_wet",255,0),
    "":("farming:dry_soil",255,0),
    "":("farming:dry_soil_wet",255,0),
    "":("farming:seed_cotton",255,0),
    "":("farming:seed_wheat",255,0),
    "":("farming:soil",255,0),
    "":("farming:soil_wet",255,0),
    "":("farming:straw",255,0),
    "":("farming:wheat_1",255,0),
    "":("farming:wheat_2",255,0),
    "":("farming:wheat_3",255,0),
    "":("farming:wheat_4",255,0),
    "":("farming:wheat_5",255,0),
    "":("farming:wheat_6",255,0),
    "":("farming:wheat_7",255,0),
    "":("farming:wheat_8",255,0),
    "":("fire:basic_flame",255,0),
    "":("fire:permanent_flame",255,0),
    "":("fireflies:firefly",255,0),
    "":("fireflies:firefly_bottle",255,0),
    "":("fireflies:hidden_firefly",255,0),
    "":("flowers:chrysanthemum_green",255,0),
    "":("flowers:dandelion_white",255,0),
    "":("flowers:dandelion_yellow",255,0),
    "":("flowers:geranium",255,0),
    "":("flowers:mushroom_brown",255,0),
    "":("flowers:mushroom_red",255,0),
    "":("flowers:rose",255,0),
    "":("flowers:tulip",255,0),
    "":("flowers:tulip_black",255,0),
    "":("flowers:viola",255,0),
    "":("flowers:waterlily",255,0),
    "":("flowers:waterlily_waving",255,0),
    "":("tnt:boom",255,0),
    "":("tnt:gunpowder",255,0),
    "":("tnt:gunpowder_burning",255,0),
    "":("tnt:tnt",255,0),
    "":("tnt:tnt_burning",255,0),
    "":("vessels:drinking_glass",255,0),
    "":("vessels:glass_bottle",255,0),
    "":("vessels:shelf",255,0),
    "":("vessels:steel_bottle",255,0),
    "":("walls:cobble",255,0),
    "":("walls:desertcobble",255,0),
    "":("walls:mossycobble",255,0),
    "":("wool:black",255,0),
    "":("wool:blue",255,0),
    "":("wool:brown",255,0),
    "":("wool:cyan",255,0),
    "":("wool:dark_green",255,0),
    "":("wool:dark_grey",255,0),
    "":("wool:green",255,0),
    "":("wool:grey",255,0),
    "":("wool:magenta",255,0),
    "":("wool:orange",255,0),
    "":("wool:pink",255,0),
    "":("wool:red",255,0),
    "":("wool:violet",255,0),
    "":("wool:white",255,0),
    "":("wool:yellow",255,0),
    "":("xpanes:bar",255,0),
    "":("xpanes:bar_flat",255,0),
    "":("xpanes:door_steel_bar_a",255,0),
    "":("xpanes:door_steel_bar_b",255,0),
    "":("xpanes:obsidian_pane",255,0),
    "":("xpanes:obsidian_pane_flat",255,0),
    "":("xpanes:pane",255,0),
    "":("xpanes:pane_flat",255,cardinal2facedir),
    "":("xpanes:trapdoor_steel_bar",255,0),
    "":("xpanes:trapdoor_steel_bar_open",255,0),
}

stairs_table = {
    "":("stairs:slab_acacia_wood",255,0),
    "":("stairs:slab_aspen_wood",255,0),
    "":("stairs:slab_brick",255,0),
    "":("stairs:slab_bronzeblock",255,0),
    "":("stairs:slab_cobble",255,0),
    "":("stairs:slab_copperblock",255,0),
    "":("stairs:slab_desert_cobble",255,0),
    "":("stairs:slab_desert_sandstone",255,0),
    "":("stairs:slab_desert_sandstone_block",255,0),
    "":("stairs:slab_desert_sandstone_brick",255,0),
    "":("stairs:slab_desert_stone",255,0),
    "":("stairs:slab_desert_stone_block",255,0),
    "":("stairs:slab_desert_stonebrick",255,0),
    "":("stairs:slab_glass",255,0),
    "":("stairs:slab_goldblock",255,0),
    "":("stairs:slab_ice",255,0),
    "":("stairs:slab_junglewood",255,0),
    "":("stairs:slab_mossycobble",255,0),
    "":("stairs:slab_obsidian",255,0),
    "":("stairs:slab_obsidian_block",255,0),
    "":("stairs:slab_obsidian_glass",255,0),
    "":("stairs:slab_obsidianbrick",255,0),
    "":("stairs:slab_pine_wood",255,0),
    "":("stairs:slab_sandstone",255,0),
    "":("stairs:slab_sandstone_block",255,0),
    "":("stairs:slab_sandstonebrick",255,0),
    "":("stairs:slab_silver_sandstone",255,0),
    "":("stairs:slab_silver_sandstone_block",255,0),
    "":("stairs:slab_silver_sandstone_brick",255,0),
    "":("stairs:slab_snowblock",255,0),
    "":("stairs:slab_steelblock",255,0),
    "":("stairs:slab_stone",255,0),
    "":("stairs:slab_stone_block",255,0),
    "":("stairs:slab_stonebrick",255,0),
    "":("stairs:slab_straw",255,0),
    "":("stairs:slab_tinblock",255,0),
    "":("stairs:slab_wood",255,0),
    
    "":("stairs:stair_acacia_wood",255,stair2facedir),
    "":("stairs:stair_aspen_wood",255,stair2facedir),
    "brick_stairs":("stairs:stair_brick",255,stair2facedir),
    "":("stairs:stair_bronzeblock",255,stair2facedir),
    "cobblestone_stairs":("stairs:stair_cobble",255,stair2facedir),
    "":("stairs:stair_copperblock",255,stair2facedir),
    "":("stairs:stair_desert_cobble",255,stair2facedir),
    "":("stairs:stair_desert_sandstone",255,stair2facedir),
    "":("stairs:stair_desert_sandstone_block",255,stair2facedir),
    "":("stairs:stair_desert_sandstone_brick",255,stair2facedir),
    "":("stairs:stair_desert_stone",255,stair2facedir),
    "":("stairs:stair_desert_stone_block",255,stair2facedir),
    "":("stairs:stair_desert_stonebrick",255,stair2facedir),
    "":("stairs:stair_glass",255,stair2facedir),
    "":("stairs:stair_goldblock",255,stair2facedir),
    "":("stairs:stair_ice",255,stair2facedir),
    "jungle_stairs":("stairs:stair_junglewood",255,stair2facedir),
    "":("stairs:stair_mossycobble",255,stair2facedir),
    "":("stairs:stair_obsidian",255,stair2facedir),
    "":("stairs:stair_obsidian_block",255,stair2facedir),
    "":("stairs:stair_obsidian_glass",255,stair2facedir),
    "":("stairs:stair_obsidianbrick",255,stair2facedir),
    "":("stairs:stair_pine_wood",255,stair2facedir),
    "sandstone_stairs":("stairs:stair_sandstone",255,stair2facedir),
    "":("stairs:stair_sandstone_block",255,stair2facedir),
    "":("stairs:stair_sandstonebrick",255,stair2facedir),
    "":("stairs:stair_silver_sandstone",255,stair2facedir),
    "":("stairs:stair_silver_sandstone_block",255,stair2facedir),
    "":("stairs:stair_silver_sandstone_brick",255,stair2facedir),
    "":("stairs:stair_snowblock",255,stair2facedir),
    "":("stairs:stair_steelblock",255,stair2facedir),
    "stone_stairs":("stairs:stair_stone",255,stair2facedir),
    "":("stairs:stair_stone_block",255,stair2facedir),
    "stone_brick_stairs":("stairs:stair_stonebrick",255,stair2facedir),
    "":("stairs:stair_straw",255,stair2facedir),
    "":("stairs:stair_tinblock",255,stair2facedir),
    "oak_stairs":("stairs:stair_wood",255,stair2facedir),
    
    "":("stairs:stair_inner_acacia_wood",255,0),
    "":("stairs:stair_inner_aspen_wood",255,0),
    "":("stairs:stair_inner_brick",255,0),
    "":("stairs:stair_inner_bronzeblock",255,0),
    "":("stairs:stair_inner_cobble",255,0),
    "":("stairs:stair_inner_copperblock",255,0),
    "":("stairs:stair_inner_desert_cobble",255,0),
    "":("stairs:stair_inner_desert_sandstone",255,0),
    "":("stairs:stair_inner_desert_sandstone_block",255,0),
    "":("stairs:stair_inner_desert_sandstone_brick",255,0),
    "":("stairs:stair_inner_desert_stone",255,0),
    "":("stairs:stair_inner_desert_stone_block",255,0),
    "":("stairs:stair_inner_desert_stonebrick",255,0),
    "":("stairs:stair_inner_glass",255,0),
    "":("stairs:stair_inner_goldblock",255,0),
    "":("stairs:stair_inner_ice",255,0),
    "":("stairs:stair_inner_junglewood",255,0),
    "":("stairs:stair_inner_mossycobble",255,0),
    "":("stairs:stair_inner_obsidian",255,0),
    "":("stairs:stair_inner_obsidian_block",255,0),
    "":("stairs:stair_inner_obsidian_glass",255,0),
    "":("stairs:stair_inner_obsidianbrick",255,0),
    "":("stairs:stair_inner_pine_wood",255,0),
    "":("stairs:stair_inner_sandstone",255,0),
    "":("stairs:stair_inner_sandstone_block",255,0),
    "":("stairs:stair_inner_sandstonebrick",255,0),
    "":("stairs:stair_inner_silver_sandstone",255,0),
    "":("stairs:stair_inner_silver_sandstone_block",255,0),
    "":("stairs:stair_inner_silver_sandstone_brick",255,0),
    "":("stairs:stair_inner_snowblock",255,0),
    "":("stairs:stair_inner_steelblock",255,0),
    "":("stairs:stair_inner_stone",255,0),
    "":("stairs:stair_inner_stone_block",255,0),
    "":("stairs:stair_inner_stonebrick",255,0),
    "":("stairs:stair_inner_straw",255,0),
    "":("stairs:stair_inner_tinblock",255,0),
    "":("stairs:stair_inner_wood",255,0),
    
    "":("stairs:stair_outer_acacia_wood",255,0),
    "":("stairs:stair_outer_aspen_wood",255,0),
    "":("stairs:stair_outer_brick",255,0),
    "":("stairs:stair_outer_bronzeblock",255,0),
    "":("stairs:stair_outer_cobble",255,0),
    "":("stairs:stair_outer_copperblock",255,0),
    "":("stairs:stair_outer_desert_cobble",255,0),
    "":("stairs:stair_outer_desert_sandstone",255,0),
    "":("stairs:stair_outer_desert_sandstone_block",255,0),
    "":("stairs:stair_outer_desert_sandstone_brick",255,0),
    "":("stairs:stair_outer_desert_stone",255,0),
    "":("stairs:stair_outer_desert_stone_block",255,0),
    "":("stairs:stair_outer_desert_stonebrick",255,0),
    "":("stairs:stair_outer_glass",255,0),
    "":("stairs:stair_outer_goldblock",255,0),
    "":("stairs:stair_outer_ice",255,0),
    "":("stairs:stair_outer_junglewood",255,0),
    "":("stairs:stair_outer_mossycobble",255,0),
    "":("stairs:stair_outer_obsidian",255,0),
    "":("stairs:stair_outer_obsidian_block",255,0),
    "":("stairs:stair_outer_obsidian_glass",255,0),
    "":("stairs:stair_outer_obsidianbrick",255,0),
    "":("stairs:stair_outer_pine_wood",255,0),
    "":("stairs:stair_outer_sandstone",255,0),
    "":("stairs:stair_outer_sandstone_block",255,0),
    "":("stairs:stair_outer_sandstonebrick",255,0),
    "":("stairs:stair_outer_silver_sandstone",255,0),
    "":("stairs:stair_outer_silver_sandstone_block",255,0),
    "":("stairs:stair_outer_silver_sandstone_brick",255,0),
    "":("stairs:stair_outer_snowblock",255,0),
    "":("stairs:stair_outer_steelblock",255,0),
    "":("stairs:stair_outer_stone",255,0),
    "":("stairs:stair_outer_stone_block",255,0),
    "":("stairs:stair_outer_stonebrick",255,0),
    "":("stairs:stair_outer_straw",255,0),
    "":("stairs:stair_outer_tinblock",255,0),
    "":("stairs:stair_outer_wood",255,0),
}

quartz_table = {
    "quartz_block" : ("quartz:block",255,0)
}
